baseURL = 'https://go.ngs.io/'
languageCode = 'en-us'
title = 'Go Modules - ngs.io'

[params]
  description = "Custom import paths for Go modules"

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "JSON"]
  page = ["HTML"]
